let tokens = [
    { type: 'tahti', moneyValue: 0 },
    { type: 'punainen', moneyValue: 1000 },
    { type: 'punainen', moneyValue: 1000 },
    { type: 'vihrea', moneyValue: 600 },
    { type: 'vihrea', moneyValue: 600 },
    { type: 'vihrea', moneyValue: 600 },
    { type: 'keltainen', moneyValue: 300 },
    { type: 'keltainen', moneyValue: 300 },
    { type: 'keltainen', moneyValue: 300 },
    { type: 'keltainen', moneyValue: 300 },
    { type: 'rosvo', moneyValue: 0 },
    { type: 'rosvo', moneyValue: 0 },
    { type: 'rosvo', moneyValue: 0 },
    { type: 'kenka', moneyValue: 0 },
    { type: 'kenka', moneyValue: 0 },
    { type: 'kenka', moneyValue: 0 },
    { type: 'kenka', moneyValue: 0 },
    { type: 'kenka', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
    { type: 'tyhja', moneyValue: 0 },
];

export default tokens;